[package]
name = "local-sorting-actors"
version = "0.1.0"
authors = ["pbielak"]
edition = "2018"

[dependencies]
actix = "0.7"
futures = "0.1"
env_logger = "0.6"
log = "0.4"
rand = "0.6"
structopt = "0.2"
time = "0.1"
